[database]
url = "sqlite:./config/data.db?mode=rwc"
max_connections = 100
min_connections = 10
connect_timeout = 10
idle_timeout = 5
max_lifetime = 300
sqlx_logging = true

[log]
level = "INFO"
directory = "logs"
basename = "easy-kafka"
suffix = "log"