//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "connect_properties")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub connect_id: i32,
    pub property_name: String,
    pub property_value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kafka_connect::Entity",
        from = "Column::ConnectId",
        to = "super::kafka_connect::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    KafkaConnect,
}

impl Related<super::kafka_connect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KafkaConnect.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
