//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kafka_connect")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub url: String,
    pub port: i32,
    pub username: Option<String>,
    pub password: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::connect_properties::Entity")]
    ConnectProperties,
}

impl Related<super::connect_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectProperties.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
