//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "topics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    #[serde(rename = "name")]
    pub topic_name: String,

    #[serde(rename = "partitionCount")]
    pub partition: i32,
    #[serde(rename = "replicationFactor")]
    pub replica: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub properties: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
